### ISSUE TITLE
Timeout waiting for node assignment 

### ISSUE THREAD

**Issue by shrinanda** [eshepelyuk/apicurio-registry-helm#3]
Hi ,

I am trying to deploy the APICURIO registry using kafka bootstrap server on EKS. I am getting error on " time out waiting for  node assignment". Please help me with resolution.  

Added kafka bootstrap server details on values.yaml like 
=======================================
## uncomment and adjust for kafka persistence
  kafka:
     bootstrapServers: "kafka-kafka-bootstrap.kafka.svc:9093"
=======================================
Refer log file below. 
===========================================================
2021-09-15 06:18:02,572 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka version: 2.5.0                                                              ││ 2021-09-15 06:18:02,573 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka commitId: 66563e712b0b9f84                                                  │
│ 2021-09-15 06:18:02,573 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka startTimeMs: 1631686682571                                                  │
│ 2021-09-15 06:18:17,005 INFO  [io.api.reg.sto.RegistryStorageProducer] (executor-thread-1) Using RegistryStore: io.apicurio.registry.storage.impl.kafkasql │
│ 2021-09-15 06:18:32,576 INFO  [org.apa.kaf.cli.adm.int.AdminMetadataManager] (kafka-admin-client-thread | adminclient-1) [AdminClient clientId=adminclient │
│ Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.                                                       │
│ 2021-09-15 06:19:02,577 INFO  [org.apa.kaf.cli.adm.int.AdminMetadataManager] (kafka-admin-client-thread | adminclient-1) [AdminClient clientId=adminclient │
│ Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.                                                       │
│ 2021-09-15 06:19:02,578 INFO  [org.apa.kaf.cli.adm.int.AdminMetadataManager] (kafka-admin-client-thread | adminclient-1) [AdminClient clientId=adminclient │
│ Caused by: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited.                                                             │
│ 2021-09-15 06:19:02,598 WARN  [io.api.reg.met.PersistenceExceptionLivenessCheck] (main) Liveness problem suspected in PersistenceExceptionLivenessCheck be │
│ Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.                                                       │
│ 2021-09-15 06:19:02,599 INFO  [io.api.reg.met.PersistenceExceptionLivenessCheck] (main) After this event, the error counter is 1 (out of the maximum 5 all │
│ 2021-09-15 06:19:02,630 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.apache.kafka.common.errors.TimeoutExcep
<https://teams.microsoft.com/l/message/19:7b9a7b32375446cdbef042a23bb9b4db@thread.skype/1631687084766?tenantId=c337bf2a-9c18-4772-a0be-2d0457489914&amp;groupId=08d00cc9-d611-4e3b-a614-5f02c28318fe&amp;parentMessageId=1631095701885&amp;teamName=SaaS Kicking Engineers&amp;channelName=General&amp;createdTime=1631687084766>

**Comment by eshepelyuk** [comment]
Try to use non SSL connection. Probably this is the issue.
And moreover, your issue should be rather addressed to developers of the apicurio-registry.

**Comment by shrinanda** [comment]
Thank you the update. I raised ticket with apicurio registry as well. 
I need to enable with SSL connection, since kafka bootstrapserver enabled with secured connection. Based on the understanding from document that apicurio will support SSL connection as well.

**Comment by eshepelyuk** [comment]
Could you please just try it without SSL and report results here ?

**Comment by shrinanda** [comment]
Yes. without SSL , i am able to deploy the apicurio registry. Please check the log file.
[without-ssl-apicurio-registry.txt](https://github.com/eshepelyuk/apicurio-registry-helm/files/7182729/without-ssl-apicurio-registry.txt)

**Comment by kmandal-volvo** [comment]
eshepelyuk - Is there any option enabled in this helm chart for TLS enabled Kafka as persistence?

**Comment by eshepelyuk** [comment]
No, there is no.

**Comment by kmandal-volvo** [comment]
I am trying to deploy the APICURIO registry using kafka bootstrap deployed using strimzi operator on AKS. I am getting error on " org.apache.kafka.common.errors.TopicAuthorizationException: Authorization failed". In log  It is crated a system topic Created new topic: kafkasql-journal then it complaining App info kafka.admin.client for adminclient-11 unregistered. In configuration there is option to provide user .Please help me with resolution log attached.
[registry.log](https://github.com/eshepelyuk/apicurio-registry-helm/files/8115078/registry.log)
