### ISSUE TITLE
Make ingress compatible with older apiVersions

### ISSUE THREAD

**Issue by iceman91176** [eshepelyuk/apicurio-registry-helm#7]
Currently the generated ingress-manifests is working with kubernetes >= 1.19 only. I added a PR #6 that handles both older and newer versions.

**Comment by eshepelyuk** [comment]
Thanks for a contribution, but I dont have plans to support older Ingress versions, having in mind that stable version is available since 1.19 and it was released more than a year ago.
I suggest you to disable ingress generation in this chart and create ingresses outside.
