### ISSUE TITLE
Make ingress tls-secret configurable

### ISSUE THREAD

**Issue by iceman91176** [eshepelyuk/apicurio-registry-helm#8]
It would be nice if the tls-secret wuld be configurable. Currently it is hard-coded to the ingress-host-name.
I can provide a PR that makes it configurable and defaults to the host-name to be backward-compatbible.

@eshepelyuk What do you think ?

**Comment by eshepelyuk** [comment]
Hello
PR is welcome, but plz keep current behaviour as default.
